<?= $this->headLink()->prependStylesheet($this->basePath() . '/view/css/group.css'); ?>
<?= $this->render('layout/menu.phtml'); ?>
<div class="paging">
    <?php if ($countGroups): ?>
        <?= $this->paginationHelper($countGroups, $page, '/group/index/', $request); ?>
    <?php endif; ?>
</div>
<?php if (!empty($messages)): ?>
    <div class="alert alert-info">
        <?= $messages[0]; ?>
    </div>
<?php endif; ?>
<?php if ($groups): ?>
    <div class="row group-filter">
        <div class="col-lg-12">
            <?= $this->form()->openTag($form); ?>
            <?php foreach ($form as $element): ?>
                <div class="form-group col-md-2" >
                    <label><?= $element->getLabel(); ?></label>
                    <?= $this->formElement($element); ?>
                    <?= $this->formElementErrors($element); ?>
                </div>
            <?php endforeach; ?>
            <?= $this->form()->closeTag(); ?>
            <div class="form-group col-md-2" >
                <label>&nbsp;</label>
                <a href="<?= $this->url('group'); ?>" class="form-control btn btn-default">
                    <?= $this->translate('Reset Filters'); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="manage-group">
        <h1 class="text-center"><?= $this->translate('List Groups'); ?></h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?= $this->translate('Id'); ?></th>
                    <th><?= $this->translate('Name'); ?></th>
                    <th><?= $this->translate('Edit'); ?></th>
                    <th><?= $this->translate('Delete'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($groups as $group): ?>
                    <tr>
                        <td><?= $group['id']; ?></td>
                        <td><?= $group['name']; ?></td>
                        <td class="text-center">
                            <a class="btn btn-info" href="<?= $this->url('group', array('action' => 'edit', 'id' => $group['id'])); ?>">
                                <?= $this->translate('Edit'); ?>
                            </a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger" href="<?= $this->url('group', array('action' => 'delete', 'id' => $group['id'])); ?>">
                                <?= $this->translate('Delete'); ?>
                            </a>
                        </td>
                    </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<div class="manage-group text-right">
    <a class="btn btn-success" href="<?= $this->url('group', array('action' => 'add')); ?>">
        <?= $this->translate('Add Group'); ?>
    </a>
</div>
