<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?= $this->url('auth',  array('action' => 'logout')); ?>">
                        <?= $this->translate('Logout'); ?>
                    </a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="paging">
    <?= $this->paginationHelper($countUsers, $page, '/users/index/'); ?>
</div>
<div class="container">
    <h2><?= $this->translate('List Users'); ?></h2>
    <?php if ($consumers): ?>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?= $this->translate('Avatar'); ?></th>
                    <th><?= $this->translate('Id'); ?></th>
                    <th><?= $this->translate('Login'); ?></th>
                    <th><?= $this->translate('Email'); ?></th>
                    <th><?= $this->translate('Account Expired'); ?></th>
                    <th><?= $this->translate('Group'); ?></th>
                </tr>
            </thead>
            <?php foreach ($consumers as $user): ?>
                <tr>
                    <td><img src="<?= $user['avatarExtension']; ?>" alt="<?= $user['login']; ?>"></td>
                    <td><?= $user['id']; ?></td>
                    <td><?= $user['login']; ?></td>
                    <td><?= $user['email']; ?></td>
                    <td><?= $user['accountExpired']->format('Y-m-d \ H:i'); ?></td>
                    <td><?= $user['groupName'] ?: $this->translate('Group isn\'t set'); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php else: ?>
        <p><?= $this->translate('List is empty'); ?></p>
    <?php endif; ?>
</div>

