<?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-datepicker.min.css'); ?>
<?= $this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/view/js/index.js');
?>
<?= $this->render('layout/menu.phtml'); ?>
<?php if (!empty($messages)): ?>
    <div class="alert alert-info">
        <?= $messages[0]; ?>
    </div>
<?php endif; ?>
<div class="paging">
    <?php if ($countUsers): ?>
        <?= $this->paginationHelper($countUsers, $page, '/users/index/', $request); ?>
    <?php endif; ?>
</div>
<div class="row">
    <?= $this->form()->openTag($form); ?>
        <?php foreach ($form as $element): ?>
            <div class="form-group col-md-2" >
                <label><?= $element->getLabel(); ?></label>
                <?= $this->formElement($element); ?>
                <?= $this->formElementErrors($element); ?>
            </div>
        <?php endforeach; ?>
    <?= $this->form()->closeTag(); ?>
    <div class="form-group col-md-2" >
        <label>&nbsp;</label>
        <a href="<?= $this->url('home'); ?>" class="form-control btn btn-default">
            <?= $this->translate('Reset Filters'); ?>
        </a>
    </div>
</div>
<div class="container">
    <?php if ($consumers): ?>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?= $this->translate('Avatar'); ?></th>
                    <?php foreach ($fields as $field): ?>
                        <th><?= $field; ?></th>
                    <?php endforeach; ?>
                    <th><?= $this->translate('Edit'); ?></th>
                    <th><?= $this->translate('Delete'); ?></th>
                </tr>
            </thead>
            <?php foreach ($consumers as $user): ?>
                <tr>
                    <td><img src="<?= $this->avatarPathHelper($user['id'], $user['avatarExtension']); ?>" alt="<?= $user['login']; ?>"></td>
                    <td><?= $user['id']; ?></td>
                    <td><?= $user['login']; ?></td>
                    <td><?= $user['email']; ?></td>
                    <td><?= $user['accountExpired']->format('Y-m-d \ H:i'); ?></td>
                    <td><?= isset($groups[$user['groupId']]) ? $groups[$user['groupId']] : 'User without group'; ?></td>
                    <td class="text-center">
                        <a class="btn btn-info" href="<?= $this->url('user', array('action' => 'edit', 'id' => $user['id'])); ?>">
                            <?= $this->translate('Edit'); ?>
                        </a>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-danger" href="<?= $this->url('user', array('action' => 'delete', 'id' => $user['id'])); ?>">
                            <?= $this->translate('delete'); ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php else: ?>
        <div class="row">
            <h2 class="zf-green text-center"><?= $this->translate('List is empty'); ?></h2>
        </div>
    <?php endif; ?>
    <div class="row text-right">
        <a class="btn btn-success" href="<?= $this->url('user'); ?>">
            <?= $this->translate('Add User'); ?>
        </a>
    </div>
</div>

