<?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-datepicker.min.css'); ?>
<?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-datepicker.js'); ?>
<?= $this->headScript()->prependFile($this->basePath() . '/view/js/index.js'); ?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?= $this->url('auth',  array('action' => 'logout')); ?>">
                        <?= $this->translate('Logout'); ?>
                    </a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="paging">
    <?php if ($countUsers): ?>
        <?= $this->paginationHelper($countUsers, $page, '/users/index/', $request); ?>
    <?php endif; ?>
</div>
<div class="row">
    <?= $this->form()->openTag($form); ?>
        <?php foreach ($form as $element): ?>
            <div class="form-group col-md-2" >
                <label><?= $element->getLabel(); ?></label>
                <?= $this->formElement($element); ?>
                <?= $this->formElementErrors($element); ?>
            </div>
        <?php endforeach; ?>
    <?= $this->form()->closeTag(); ?>
    <div class="form-group col-md-2" >
        <label>&nbsp;</label>
        <a href="<?= $this->url('home'); ?>" class="form-control btn btn-default">
            <?= $this->translate('Reset Filters'); ?>
        </a>
    </div>
</div>
<div class="container">
    <?php if ($consumers): ?>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?= $this->translate('Avatar'); ?></th>
                    <?php foreach ($fields as $field): ?>
                        <th><?= $field; ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <?php foreach ($consumers as $user): ?>
                <tr>
                    <td><img src="<?= $user['avatarExtension']; ?>" alt="<?= $user['login']; ?>"></td>
                    <td><?= $user['id']; ?></td>
                    <td><?= $user['login']; ?></td>
                    <td><?= $user['email']; ?></td>
                    <td><?= $user['accountExpired']->format('Y-m-d \ H:i'); ?></td>
                    <td><?= isset($groups[$user['groupId']]) ? $groups[$user['groupId']] : 'User without group'; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php else: ?>
        <div class="row">
            <h2 class="zf-green text-center"><?= $this->translate('List is empty'); ?></h2>
        </div>
    <?php endif; ?>
</div>

